"""
Django settings for crud project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&kevf^6&_=8+$46mx35d^wjs#1-2ttrnn3e(z3_7mu)rm5)9sq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = [
    'modeltranslation',                # 1. Toujours avant django.contrib.admin pour l'admin integration
    'unfold',                          # 2. Après modeltranslation, mais avant admin
    'unfold.contrib.import_export',    # 3. Décommente et place ici (obligatoire pour toolbar + import/export)
    'django.contrib.admin',            # 4. Après unfold et modeltranslation
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'debug_toolbar',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    "ckeditor",
    "ckeditor_uploader",

    'import_export',                  

    'app',
    'app.products',
]

#INSTALLED_APPS = [
#    'unfold',
#    'unfold.contrib.import_export', # ← Indispensable pour voir les boutons Import/Export avec Unfold
#    'django.contrib.admin',
#    'django.contrib.auth',
#    'django.contrib.contenttypes',
#    'django.contrib.sessions',
#    'django.contrib.messages',
#    'django.contrib.staticfiles',
    
    
#    'modeltranslation',
#    'debug_toolbar',
#    'rest_framework',
#    'rest_framework_simplejwt',
#    'drf_spectacular',
#    'drf_spectacular_sidecar',
#    'ckeditor',
#    'ckeditor_uploader',
    
#    'import_export',
    
#    'app',
#    'app.products',
#  ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ROOT_URLCONF = 'crud.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crud.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

#LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = BASE_DIR / 'staticfiles'


STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
CKEDITOR_UPLOAD_PATH = "uploads/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# === IMPORT CONFIG UNFOLD ===
from crud.config.unfold_config import UNFOLD

## pour éviter le warning "variable not used" dans VS Code
UNFOLD_CONFIG = UNFOLD

# === IMPORT CONFIG REST FRAMEWORK ===
from crud.config.restframework_config import SPECTACULAR_SETTINGS, REST_FRAMEWORK, SIMPLE_JWT


# === INTERNATIONALISATION ===
from django.utils.translation import gettext_lazy as _

USE_I18N = True
USE_TZ = True
TIME_ZONE = 'UTC'

LANGUAGES = [
    ('fr', 'Français'),
    ('en', 'Anglais'),
    ('de', 'Allemand'),
]

LANGUAGE_CODE = 'en'  # Langue par défaut

MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'
MODELTRANSLATION_FALLBACK_LANGUAGES = {
    'default': ('en',),
}

LOCALE_PATHS = [
    BASE_DIR / 'locale', 
]

# === LOGGING (fichier + console) ===
from crud.config.logging_config import LOGGING  # noqa: F401

# === DEBUG TOOLBAR (panels + config) ===
from crud.config.debug_toolbar_config import DEBUG_TOOLBAR_PANELS, DEBUG_TOOLBAR_CONFIG

# On force l’activation des panels personnalisés
import debug_toolbar.settings as dt_settings
dt_settings.PANELS_DEFAULTS = DEBUG_TOOLBAR_PANELS

DEBUG_TOOLBAR_CONFIG = DEBUG_TOOLBAR_CONFIG

# Sécurité
INTERNAL_IPS = ["127.0.0.1", "::1"]